---
# tasks file for mysql_db
- name: Install MySQL database
  apt: name={{ item }} state=present
  with_items:
    - default-mysql-server
    - default-mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present

- name: Create Database User
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'